from __future__ import annotations

from typing import Protocol

from trainctl.core.models import Checkpoint, EvalJob, MetricPoint, Run


class StateStore(Protocol):
    def save_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def list_runs(self, limit: int = 100) -> list[Run]: ...
    def save_metric(self, point: MetricPoint) -> None: ...
    def latest_metric(self, run_id: str, name: str) -> MetricPoint | None: ...
    def metric_history(self, run_id: str, name: str, limit: int | None = None) -> list[MetricPoint]: ...
    def save_checkpoint(self, checkpoint: Checkpoint) -> None: ...
    def list_checkpoints(self, run_id: str) -> list[Checkpoint]: ...
    def save_eval_job(self, job: EvalJob) -> None: ...

